name: flutter_braintree_platform_interface
description: Flutter plugin that wraps the native Braintree SDKs. Enables payments with credit cards, PayPal, Google Pay and more.
version: 1.0.0
homepage: https://github.com/pikaju/flutter-braintree/flutter-braintree-platform-interface

environment:
  sdk: ">=2.2.2 <3.0.0"
  flutter: ">=1.10.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  meta: ">= 1.0.0 <2.0.0"

dev_dependencies:
  pedantic: ^1.10.0