name: flutter_braintree_web
description: Flutter plugin that wraps the native Braintree SDKs. Enables payments with credit cards, PayPal, Google Pay and more.
version: 1.0.0
homepage: https://github.com/pikaju/flutter-braintree/flutter-braintree-web

environment:
  sdk: ">=2.2.2 <3.0.0"
  flutter: ">=1.10.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  meta: ">= 1.0.0 <2.0.0"
  flutter_braintree_platform_interface:
    path: /Users/daniel/OneDrive/projects/flutter-braintree/flutter-braintree-platform-interface

flutter:
  plugin:
    platforms:
      web:
        pluginClass: FlutterBraintreePlugin
        fileName: flutter_brintree_dev.dart